// Invoice generation logic
const Invoice = {
  // Generate invoice number based on date
  generateNumber(username) {
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    return `${date}-${username}`;
  },

  // Generate filename
  generateFilename(username) {
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    return `${date}.${username}.invoice.yaml`;
  },

  // Format date as YYYY-MM-DD
  formatDate(date) {
    return date.toISOString().split('T')[0];
  },

  // Format currency
  formatCurrency(amount, currency) {
    const symbol = currency === 'USD' ? '$' : 'R$';
    return `${symbol}${amount.toFixed(2)}`;
  },

  // Generate YAML content
  generateYAML(data) {
    const {
      username,
      contractorCompany,
      contractorId,
      bankInfo,
      clientCompany,
      issues,
      totalHours,
      hourlyRate,
      currency,
      paymentMethod
    } = data;

    const issueDate = new Date();
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 7);

    const totalAmount = totalHours * hourlyRate;

    // Build YAML manually for proper formatting
    let yaml = `# Invoice
# Generated by VibiInvoices

invoice:
  number: "${this.generateNumber(username)}"
  issue_date: "${this.formatDate(issueDate)}"
  due_date: "${this.formatDate(dueDate)}"
  currency: "${currency}"

contractor:
  company: "${contractorCompany}"
${contractorId ? `  tax_id: "${contractorId}"\n` : ''}  bank_info: |
${bankInfo.split('\n').map(line => `    ${line}`).join('\n')}

client:
  company: "${clientCompany}"

service:
  description: "Completar as issues de GitHub listadas abaixo:"
  issues:
${issues.map(issue => `    - url: "${issue.url}"
      title: "${issue.title.replace(/"/g, '\\"')}"
      hours: ${issue.hours || 0}`).join('\n')}

  total_hours: ${totalHours}
  hourly_rate: ${hourlyRate}
  total_amount: ${totalAmount.toFixed(2)}

payment:
  method: "${paymentMethod}"
  status: "pending"
`;

    return yaml;
  },

  // Parse invoice YAML to get summary info
  parseInvoiceSummary(filename, content) {
    // Simple regex parsing for display
    const dateMatch = filename.match(/^(\d{4}-\d{2}-\d{2})/);
    const amountMatch = content.match(/total_amount:\s*([\d.]+)/);
    const clientMatch = content.match(/client:\s*\n\s*company:\s*"([^"]+)"/);
    const hoursMatch = content.match(/total_hours:\s*([\d.]+)/);

    return {
      date: dateMatch ? dateMatch[1] : 'Unknown',
      amount: amountMatch ? parseFloat(amountMatch[1]) : 0,
      client: clientMatch ? clientMatch[1] : 'Unknown',
      hours: hoursMatch ? parseFloat(hoursMatch[1]) : 0
    };
  }
};
